import { CAST } from '../content/messages'
import type { Level } from '../game/types'
import { C, FOOTER, SUBTITLE, TITLE, decor, panel } from './kit'

export const level07: Level = {
  id: 'final-v2',
  title: 'Final_v2',
  brief: 'Strategy slide formatting',
  sender: { ...CAST.sarah, time: '16:41' },
  message: ['Few formatting tweaks.', 'Should only take 5 mins.'],
  filename: 'Strategy_Final_v2.pptx',
  filenameAfter: 'Strategy_Final_v2_FINAL.pptx',
  canvas: { width: 960, height: 600, surface: 'slide' },
  shapes: [
    {
      id: 'title',
      kind: 'text',
      x: 74,
      y: 37,
      width: 520,
      height: 40,
      content: 'Strategic Priorities',
      target: { x: 60, y: 44 },
      style: TITLE,
    },
    decor({
      id: 'subtitle',
      kind: 'text',
      x: 60,
      y: 88,
      width: 420,
      height: 18,
      content: 'FY26 · draft for discussion',
      style: SUBTITLE,
    }),
    decor({
      id: 'arrow1',
      kind: 'arrow',
      x: 308,
      y: 192,
      width: 44,
      height: 28,
      style: { color: C.ink3 },
    }),
    decor({
      id: 'arrow2',
      kind: 'arrow',
      x: 608,
      y: 192,
      width: 44,
      height: 28,
      style: { color: C.ink3 },
    }),
    {
      id: 'b1',
      kind: 'roundedRectangle',
      x: 60,
      y: 150,
      width: 240,
      height: 112,
      content: 'GROW CORE',
      movable: false,
      style: { ...panel(C.slate, C.line), color: C.ink2, tracking: 0.9 },
    },
    {
      id: 'b2',
      kind: 'roundedRectangle',
      x: 352,
      y: 157,
      width: 224,
      height: 112,
      content: 'SCALE DIGITAL',
      target: { x: 360, y: 150, width: 240 },
      resizable: true,
      style: { ...panel(), tracking: 0.9 },
    },
    {
      id: 'b3',
      kind: 'roundedRectangle',
      x: 668,
      y: 163,
      width: 240,
      height: 112,
      content: 'SIMPLIFY OPS',
      target: { x: 660, y: 150 },
      style: { ...panel(), tracking: 0.9 },
    },
    {
      id: 'chart',
      kind: 'chart',
      x: 52,
      y: 331,
      width: 380,
      height: 190,
      content: 'Value at stake',
      bars: [0.42, 0.61, 0.55, 0.78, 0.9],
      target: { x: 60, y: 320 },
      style: { fill: C.paper, border: C.line, radius: 4, accent: C.blue },
    },
    {
      id: 'table',
      kind: 'table',
      x: 528,
      y: 314,
      width: 356,
      height: 190,
      content: 'Owners',
      rows: [
        ['Grow core', 'Commercial'],
        ['Scale digital', 'Technology'],
        ['Simplify ops', 'Operations'],
      ],
      target: { x: 520, y: 320, width: 380 },
      resizable: true,
      style: { fill: C.paper, border: C.line, radius: 4 },
    },
    {
      id: 'footer',
      kind: 'text',
      x: 68,
      y: 556,
      width: 420,
      height: 18,
      content: 'Strictly confidential — internal use only.',
      target: { x: 60, y: 548 },
      style: FOOTER,
    },
  ],
  constraints: [
    { kind: 'alignTop', ids: ['b1', 'b2', 'b3'], label: 'Boxes top aligned' },
    { kind: 'equalWidth', ids: ['b1', 'b2', 'b3'], tolerance: 2, label: 'Equal box widths' },
    { kind: 'equalSpacingX', ids: ['b1', 'b2', 'b3'], tolerance: 2, label: 'Equal gaps' },
    { kind: 'alignTop', ids: ['chart', 'table'], label: 'Chart and table aligned' },
    { kind: 'equalWidth', ids: ['chart', 'table'], tolerance: 2 },
    { kind: 'equalHeight', ids: ['chart', 'table'], tolerance: 2 },
  ],
  twists: [
    {
      interlude: ['Perfect.'],
      notice: {
        from: 'Sarah',
        role: 'VP, Strategy',
        time: '17:02',
        text: 'One more. Legal want the disclaimer on the right.',
      },
      ops: [{ kind: 'retarget', id: 'footer', target: { x: 480, y: 548 } }],
    },
    {
      interlude: ['Great.'],
      notice: {
        from: 'Alex',
        role: 'Design',
        time: '17:26',
        text: 'The chart and the table should be the same height.',
      },
      ops: [{ kind: 'resize', id: 'table', height: 168 }],
      systemNote: 'Layout recalculated on open.',
    },
  ],
  completion: ['Approved.'],
}
