import { CAST } from '../content/messages'
import type { Level } from '../game/types'
import { C, SUBTITLE, TITLE, decor, panel } from './kit'

export const level06: Level = {
  id: 'senior-management',
  title: 'Senior management',
  brief: 'Delivery approach',
  priority: 'urgent',
  sender: { ...CAST.sarah, time: '14:55' },
  message: ['CEO is looking at this in 5 mins.', 'Quick one.'],
  filename: 'Delivery_Approach_final_v2.pptx',
  canvas: { width: 960, height: 600, surface: 'slide' },
  countdown: 300,
  countdownLabel: 'CEO review in',
  shapes: [
    decor({
      id: 'title',
      kind: 'text',
      x: 80,
      y: 52,
      width: 460,
      height: 32,
      content: 'Delivery Approach',
      style: TITLE,
    }),
    decor({
      id: 'subtitle',
      kind: 'text',
      x: 80,
      y: 88,
      width: 460,
      height: 18,
      content: 'Three phases',
      style: SUBTITLE,
    }),
    decor({
      id: 'arrow1',
      kind: 'arrow',
      x: 470,
      y: 222,
      width: 20,
      height: 26,
      style: { color: C.ink3 },
    }),
    decor({
      id: 'arrow2',
      kind: 'arrow',
      x: 470,
      y: 342,
      width: 20,
      height: 26,
      style: { color: C.ink3 },
    }),
    {
      id: 'p1',
      kind: 'roundedRectangle',
      x: 330,
      y: 130,
      width: 300,
      height: 90,
      content: 'DISCOVER',
      movable: false,
      style: { ...panel(C.slate, C.line), color: C.ink2, tracking: 1 },
    },
    {
      id: 'p2',
      kind: 'roundedRectangle',
      x: 372,
      y: 256,
      width: 300,
      height: 90,
      content: 'DEFINE',
      target: { x: 330, y: 250 },
      style: { ...panel(), tracking: 1 },
    },
    {
      id: 'p3',
      kind: 'roundedRectangle',
      x: 311,
      y: 366,
      width: 300,
      height: 90,
      content: 'DELIVER',
      target: { x: 330, y: 370 },
      style: { ...panel(), tracking: 1 },
    },
  ],
  constraints: [
    { kind: 'alignCenterX', ids: ['p1', 'p2', 'p3'], label: 'Shared centre line' },
    { kind: 'equalSpacingY', ids: ['p1', 'p2', 'p3'], tolerance: 2 },
  ],
  twists: [
    {
      interlude: ['Thanks.'],
      notice: {
        from: 'Sarah',
        role: 'VP, Strategy',
        time: '15:12',
        text: 'CEO wants it to start higher on the slide.',
      },
      ops: [
        { kind: 'place', id: 'p1', y: 106 },
        { kind: 'place', id: 'arrow1', y: 198 },
        { kind: 'place', id: 'arrow2', y: 318 },
        { kind: 'retarget', id: 'p2', target: { x: 330, y: 226 } },
        { kind: 'retarget', id: 'p3', target: { x: 330, y: 346 } },
      ],
    },
  ],
  completion: ['Thanks.', 'He only looked at the first slide.'],
}
